version: '3.8'

services:

  # 🐘 PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: analytics-postgres

    # متغيرات البيئة (Environment Variables)
    environment:
      - POSTGRES_USER=admin                
      - POSTGRES_PASSWORD=YourStrong@Passw0rd123  
      - POSTGRES_DB=AnalyticsDB             

    # (Ports)
    ports:
      - "5432:5432"

    
    volumes:
      - postgres-data:/var/lib/postgresql/data

    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d AnalyticsDB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

   
    networks:
      - analytics-network

 
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: analytics-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"    # للـ AMQP Protocol 
      - "15672:15672"  # للـ Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - analytics-network

# Volumes 
volumes:
  postgres-data:
  rabbitmq-data:

#Networks 
networks:
  analytics-network:
    driver: bridge
